# Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
data3 = pd.read_excel('data/Data_Altar_120326_corrected.xlsx')
data2 = pd.read_excel('data/Data_Altar_21112025_corrected.xlsx')
data1 = pd.read_excel('data/Data_Altar_140225_corrected.xlsx')

In [17]:
data1

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,d18OError,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,18536,No,2025-02-14 12:48:07,Tommaso Di Rocco,MAT253Plus,SanCarlos_pos01,San Carlos Olivine (olivine): 0820M,2.703,5.263,0.002,...,4,4994,4983,1.976,49.319489,5.3722,-47.4,5.357821,2.781530,2.785402
1,18535,No,2025-02-14 11:28:49,Tommaso Di Rocco,MAT253Plus,wholeD2004-11_pos11,Mafic volcanics,2.951,5.742,0.002,...,4,4966,4963,2.081,46.304247,5.8512,-51.4,5.834148,3.029030,3.033622
2,18534,No,2025-02-14 09:39:36,Tommaso Di Rocco,MAT253Plus,wholeD2004-3_pos04,Mafic volcanics,2.792,5.439,0.002,...,4,4982,4987,1.920,40.128417,5.5482,-51.4,5.532865,2.869953,2.874075
3,18533,No,2025-02-14 06:01:17,Tommaso Di Rocco,MAT253Plus,cpxD2004-12_pos10,Clinopyroxene,2.626,5.127,0.002,...,4,4875,4929,1.715,46.877343,5.2362,-52.4,5.222539,2.705100,2.708763
4,18532,No,2025-02-14 04:08:18,Tommaso Di Rocco,MAT253Plus,opxD2004-4_pos07,Orthopyroxene,3.360,6.534,0.002,...,4,4988,4997,2.050,55.190951,6.6432,-59.4,6.621231,3.436610,3.442522
5,18531,No,2025-02-14 02:19:02,Tommaso Di Rocco,MAT253Plus,cpxD2004-4_pos06,Clinopyroxene,3.159,6.136,0.002,...,5,4969,4971,1.663,45.134658,6.2452,-53.4,6.225780,3.233812,3.239046
6,18530,No,2025-02-14 00:29:52,Tommaso Di Rocco,MAT253Plus,SanCarlos_pos02,San Carlos Olivine (olivine): 0820M,2.682,5.219,0.003,...,4,4919,4938,2.024,46.429034,5.3282,-45.4,5.314055,2.760421,2.764235
7,18529,No,2025-02-13 22:40:36,Tommaso Di Rocco,MAT253Plus,cpxD2004-5_pos05,Clinopyroxene,3.065,5.950,0.002,...,3,4984,4978,2.019,55.479469,6.0592,-47.4,6.040917,3.142204,3.147146
8,18528,No,2025-02-13 20:51:13,Tommaso Di Rocco,MAT253Plus,olivineD2004-11_pos09,Olivine,2.605,5.097,0.002,...,3,4940,4931,2.040,53.897045,5.2062,-58.4,5.192695,2.683343,2.686946
9,18527,No,2025-02-13 19:01:51,Tommaso Di Rocco,MAT253Plus,olivineD2004-3_pos08,Olivine,2.446,4.781,0.002,...,5,5000,5004,1.402,38.549035,4.8902,-50.4,4.878282,2.525333,2.528524
10,18525,No,2025-02-13 17:12:38,Tommaso Di Rocco,MAT253Plus,SanCarlos_pos14,San Carlos Olivine (olivine): 0820M,2.486,4.861,0.002,...,5,4957,4968,2.008,53.676098,4.9702,-53.4,4.957889,2.564366,2.567656
11,18524,No,2025-02-13 15:20:24,Tommaso Di Rocco,MAT253Plus,SanCarlos_pos13,San Carlos Olivine (olivine): 0820M,2.534,4.962,0.002,...,4,4967,4958,2.004,53.116486,5.0712,-58.4,5.058385,2.612427,2.615843
12,18523,No,2025-02-13 13:30:22,Tommaso Di Rocco,MAT253Plus,SanCarlos_pos12,San Carlos Olivine (olivine): 0820M,2.704,5.279,0.002,...,4,4984,4990,2.095,67.813743,5.3882,-55.4,5.373736,2.781932,2.785806

In [19]:
data2

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,d18OError,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,20977,No,2025-11-22 13:19:00,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos14,San Carlos Olivine (olivine): 0820M,2.740,5.322,0.002,...,5,4921,4924,2.130,87.599229,5.413167,-47.5,5.398568,2.802944,2.806876
1,20976,No,2025-11-22 11:59:00,Tommaso Di Rocco,MAT253Plus,SanCarlos0820_pos13,San Carlos Olivine (olivine): 0820M,2.688,5.219,0.002,...,4,4982,4977,1.839,87.520549,5.310167,-45.5,5.296117,2.750850,2.754637
2,20975,No,2025-11-22 10:19:00,Tommaso Di Rocco,MAT253Plus,D2004-12-bulk_pos12,Mafic volcanics,2.482,4.853,0.002,...,5,4684,4723,1.812,58.343725,4.944167,-58.5,4.931984,2.545588,2.548831
3,20974,No,2025-11-22 08:38:00,Tommaso Di Rocco,MAT253Plus,D2004-8-bulk_pos11,Mafic volcanics,3.028,5.884,0.002,...,5,4975,4962,2.290,91.250722,5.975167,-55.5,5.957386,3.090000,3.094779
4,20973,No,2025-11-22 06:58:00,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos10,San Carlos Olivine (olivine): 0820M,2.679,5.191,0.002,...,4,4958,4961,1.884,107.124367,5.282167,-39.5,5.268265,2.742144,2.745907
5,20971,No,2025-11-22 03:36:00,Tommaso Di Rocco,MAT253Plus,D2004-5-bulk_pos08,Mafic volcanics,3.227,6.255,0.002,...,5,4976,4968,1.865,78.215605,6.346167,-52.5,6.326115,3.287688,3.293099
6,20970,No,2025-11-22 01:52:00,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos07,San Carlos Olivine (olivine): 0820M,2.632,5.115,0.002,...,4,4963,4969,2.099,126.207306,5.206167,-46.5,5.192661,2.695225,2.698861
7,20966,No,2025-11-21 19:09:00,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos03,San Carlos Olivine (olivine): 0820M,2.592,5.073,0.002,...,5,4951,4954,1.845,97.875139,5.164167,-64.5,5.150878,2.655164,2.658692
8,20965,No,2025-11-21 17:29:00,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos02,San Carlos Olivine (olivine): 0820M,2.492,4.889,0.002,...,3,4977,4979,2.302,139.617617,4.980167,-68.5,4.967807,2.554502,2.557767

In [21]:
data3

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,CapD17O,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,21707,No,2026-03-12 11:09:43,Tommaso Di Rocco,MAT253Plus,N-W-1_pos12,Mafic plutonics,2.545,4.964,-73,...,3,4919,4955,1.870,101.017778,4.8432,-60,4.831509,2.491037,2.494142
1,21706,No,2026-03-12 06:59:35,Tommaso Di Rocco,MAT253Plus,N-H-1_pos11,Mafic volcanics,2.543,4.941,-63,...,5,4951,4948,1.815,101.458666,4.8202,-50,4.808620,2.488951,2.492051
2,21704,No,2026-03-12 03:43:42,Tommaso Di Rocco,MAT253Plus,D2004_7_pos09,Mafic volcanics,2.962,5.747,-68,...,4,4915,4903,1.810,67.372657,5.6262,-55,5.610432,2.907308,2.911538
3,21708,No,2026-03-12 12:49:47,Tommaso Di Rocco,MAT253Plus,N-W-1-ol_pos13,Olivine,2.665,5.186,-70,...,5,4961,4957,2.130,113.279657,5.0652,-57,5.052415,2.610675,2.614086
4,21709,No,2026-03-12 14:09:17,Tommaso Di Rocco,MAT253Plus,SanCarlos1023f_pos14,San Carlos Olivine (olivine): 0820M,2.758,5.355,-65,...,4,4933,4924,1.907,101.923960,5.2342,-52,5.220549,2.704450,2.708110
5,21705,No,2026-03-12 05:21:39,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos10,San Carlos Olivine (olivine): 0820M,2.772,5.387,-69,...,5,4946,4937,2.067,116.484850,5.2662,-56,5.252382,2.717258,2.720953
6,21702,No,2026-03-12 00:27:43,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos07,San Carlos Olivine (olivine): 0820M,2.752,5.337,-62,...,4,4965,4962,2.079,119.743524,5.2162,-49,5.202643,2.697995,2.701638
7,21698,No,2026-03-11 17:56:26,Tommaso Di Rocco,MAT253Plus,SanCarlos1023_pos03,San Carlos Olivine (olivine): 0820M,2.727,5.284,-59,...,5,5011,5010,1.969,117.421385,5.1632,-46,5.149916,2.673156,2.676732
8,21697,No,2026-03-11 16:18:41,Tommaso Di Rocco,MAT253Plus,SanCarlos1023f_pos02,San Carlos Olivine (olivine): 0820M,2.761,5.371,-70,...,4,4945,4944,1.847,101.824793,5.2502,-57,5.236466,2.707854,2.711523

In [ ]:
bulk_rock_data = pd.DataFrame()